_homepage:
    pattern:  /
    defaults: { _controller: "CostoSystemBundle:Home:index" }

_gasto:
    resource: "@CostoSystemBundle/Resources/config/routing/gasto.yml"
    prefix:   /gasto

_cuenta:
    resource: "@CostoSystemBundle/Resources/config/routing/cuenta.yml"
    prefix:   /cuenta

_venta:
    resource: "@CostoSystemBundle/Resources/config/routing/venta.yml"
    prefix:   /venta

_report:
    pattern:  /report
    defaults: { _controller: CostoSystemBundle:Informe:index }

_report_gen:
    pattern:  /gen
    defaults: { _controller: CostoSystemBundle:Informe:report }