_homepage:
    pattern:  /
    defaults: { _controller: "CostoSystemBundle:Home:index" }

_venta:
    resource: "@CostoSystemBundle/Controller/AjusteVentaController.php"
    type:     annotation
    prefix:   /

_gasto:
    resource: "@CostoSystemBundle/Resources/config/routing/gasto.yml"
    prefix:   /gasto

_cuenta:
    resource: "@CostoSystemBundle/Resources/config/routing/cuenta.yml"
    prefix:   /cuenta