parameters:
#    costo_system.example.class: Costo\SystemBundle\Example

services:
#    costo_system.example:
#        class: %costo_system.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
