# Rutas para gestionar todas las acciones de las entidades de tipo Ciudad
# Generado automáticamente por el comando generate:doctrine:crud
index_cuenta:
    pattern:  /
    defaults: { _controller: "CostoSystemBundle:Cuenta:index" }

show_cuenta:
    pattern:  /{id}/show
    defaults: { _controller: "CostoSystemBundle:Cuenta:show" }

new_cuenta:
    pattern:  /new
    defaults: { _controller: "CostoSystemBundle:Cuenta:new" }

create_cuenta:
    pattern:  /create
    defaults: { _controller: "CostoSystemBundle:Cuenta:create" }
    requirements: { _method: post }

edit_cuenta:
    pattern:  /{id}/edit
    defaults: { _controller: "CostoSystemBundle:Cuenta:edit" }

update_cuenta:
    pattern:  /{id}/update
    defaults: { _controller: "CostoSystemBundle:Cuenta:update" }
    requirements: { _method: post }

delete_cuenta:
    pattern:  /{id}/delete
    defaults: { _controller: "CostoSystemBundle:Cuenta:delete" }
    requirements: { _method: post }
