# Rutas para gestionar todas las acciones de las entidades de tipo Ciudad
# Generado automáticamente por el comando generate:doctrine:crud
index_gasto:
    pattern:  /
    defaults: { _controller: "CostoSystemBundle:Gasto:index" }

show_gasto:
    pattern:  /{id}/show
    defaults: { _controller: "CostoSystemBundle:Gasto:show" }

new_gasto:
    pattern:  /new
    defaults: { _controller: "CostoSystemBundle:Gasto:new" }

create_gasto:
    pattern:  /create
    defaults: { _controller: "CostoSystemBundle:Gasto:create" }
    requirements: { _method: post }

edit_gasto:
    pattern:  /{id}/edit
    defaults: { _controller: "CostoSystemBundle:Gasto:edit" }

update_gasto:
    pattern:  /{id}/update
    defaults: { _controller: "CostoSystemBundle:Gasto:update" }
    requirements: { _method: post }

delete_gasto:
    pattern:  /{id}/delete
    defaults: { _controller: "CostoSystemBundle:Gasto:delete" }
    requirements: { _method: post }
