# Rutas para gestionar todas las acciones de las entidades de tipo Ciudad
# Generado automáticamente por el comando generate:doctrine:crud
backend_ciudad:
    pattern:  /
    defaults: { _controller: "CostoSystemBundle:Gasto:index" }

backend_ciudad_show:
    pattern:  /{id}/show
    defaults: { _controller: "CostoSystemBundle:Gasto:show" }

backend_ciudad_new:
    pattern:  /new
    defaults: { _controller: "CostoSystemBundle:Gasto:new" }

backend_ciudad_create:
    pattern:  /create
    defaults: { _controller: "CostoSystemBundle:Gasto:create" }
    requirements: { _method: post }

backend_ciudad_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CostoSystemBundle:Gasto:edit" }

backend_ciudad_update:
    pattern:  /{id}/update
    defaults: { _controller: "CostoSystemBundle:Gasto:update" }
    requirements: { _method: post }

backend_ciudad_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CostoSystemBundle:Gasto:delete" }
    requirements: { _method: post }
